//! `RsiLoop` — a recursive self-improvement (RSI) loop wired on top of
//! [`InvasionFitnessScorer`](crate::invasion_fitness::InvasionFitnessScorer).
//!
//! This closes the measure→select→mutate→remeasure loop that the ATLAS plan
//! (Pathway 3, genetic + memetic RSI) calls for: candidate corpora / prompt
//! strategies are scored by Champagnat invasion fitness against the resident
//! population, the survivors are kept (invasion criterion `f(y) > 0`), offspring
//! are generated by a pluggable [`Mutator`], re-evaluated by a pluggable
//! [`Evaluator`], and accepted only if they can invade — yielding a monotone,
//! convergent improvement trajectory (Champagnat O(1/√T)).
//!
//! # Real vs scaffold
//! The loop itself is production logic. The two plug-in traits are where the
//! real system meets ATLAS:
//! - [`Evaluator`] — a real impl calls `atlas eval` / the hard eval probe on the
//!   live model and returns a measured success rate. The provided
//!   [`SyntheticEvaluator`] returns a deterministic fitness-landscape score so the
//!   loop is unit-testable with zero inference / zero serving state.
//! - [`Mutator`] — a real impl edits prompt templates / corpus entries. The
//!   provided [`SyntheticMutator`] nudges a candidate's trait vector toward the
//!   (unknown-to-the-loop) optimum with deterministic pseudo-random steps.
//!
//! No inference, no network, no serving change: this module is pure CPU logic and
//! is fully covered by the tests at the bottom of the file.

use crate::invasion_fitness::{FitnessItem, InvasionFitnessConfig, InvasionFitnessScorer};

/// A candidate strategy in the RSI population.
#[derive(Debug, Clone)]
pub struct Candidate {
    /// Stable identifier (e.g. a prompt-template name or corpus-slice id).
    pub id: String,
    /// Free-form "genome": the tunable trait vector a [`Mutator`] perturbs and the
    /// [`Evaluator`] reads. In a real system this encodes prompt / sampling knobs.
    pub genome: Vec<f32>,
    /// Resource cost proxy (≥ 0) — e.g. mean completion tokens / latency.
    pub cost: f32,
    /// Equilibrium pheromone weight (resident density proxy for the fitness term).
    pub pheromone_weight: f32,
    /// Last measured success rate ∈ [0, 1] (filled by the [`Evaluator`]).
    pub success_rate: f32,
}

impl Candidate {
    /// Build the [`FitnessItem`] view the invasion-fitness scorer consumes.
    /// The genome doubles as the semantic embedding for the competition term.
    fn as_fitness_item(&self) -> FitnessItem {
        FitnessItem {
            success_rate: self.success_rate,
            cost: self.cost,
            embedding: self.genome.clone(),
            pheromone_weight: self.pheromone_weight,
        }
    }
}

/// Measures a candidate's success rate ∈ [0, 1].
///
/// Real impl: run `atlas eval` / the hard probe against the live model and return
/// the fraction correct. Must be deterministic for a fixed candidate so the loop
/// is reproducible.
pub trait Evaluator {
    /// Return the measured success rate for `candidate` (∈ [0, 1]).
    fn evaluate(&self, candidate: &Candidate) -> f32;
}

/// Produces an offspring candidate from a parent (memetic mutation).
///
/// Real impl: edit the prompt template / corpus slice `parent` encodes. The scaffold
/// perturbs the genome deterministically.
pub trait Mutator {
    /// Generate one offspring from `parent`, using `seed` for reproducible variation.
    fn mutate(&self, parent: &Candidate, seed: u64) -> Candidate;
}

/// Per-generation summary of the RSI trajectory.
#[derive(Debug, Clone, PartialEq)]
pub struct GenerationStats {
    /// 0-based generation index.
    pub generation: usize,
    /// Number of survivors carried into this generation.
    pub population: usize,
    /// Mean invasion fitness of the population.
    pub mean_fitness: f32,
    /// Best invasion fitness in the population.
    pub max_fitness: f32,
    /// Mean measured success rate of the population.
    pub mean_success: f32,
    /// Best measured success rate found so far (hall-of-fame; provably
    /// non-decreasing — this is the capability signal of the RSI loop).
    pub best_success: f32,
    /// Id of the current best candidate.
    pub best_id: String,
    /// How many offspring were accepted this generation (could invade: `f > 0`
    /// and strictly improved on the parent they replaced).
    pub accepted: usize,
}

/// Configuration for the [`RsiLoop`].
#[derive(Debug, Clone)]
pub struct RsiConfig {
    /// Number of survivors kept each generation (elitist selection).
    pub survivors: usize,
    /// Offspring generated per survivor each generation.
    pub offspring_per_survivor: usize,
    /// Invasion-fitness config passed to the scorer.
    pub fitness: InvasionFitnessConfig,
}

impl Default for RsiConfig {
    fn default() -> Self {
        Self {
            survivors: 4,
            offspring_per_survivor: 2,
            fitness: InvasionFitnessConfig::default(),
        }
    }
}

/// The recursive self-improvement loop.
pub struct RsiLoop<E: Evaluator, M: Mutator> {
    config: RsiConfig,
    scorer: InvasionFitnessScorer,
    evaluator: E,
    mutator: M,
    seed: u64,
}

impl<E: Evaluator, M: Mutator> RsiLoop<E, M> {
    /// Create a loop with the given evaluator/mutator and config.
    pub fn new(config: RsiConfig, evaluator: E, mutator: M) -> Self {
        let scorer = InvasionFitnessScorer::new(config.fitness.clone());
        Self { config, scorer, evaluator, mutator, seed: 0x9E3779B97F4A7C15 }
    }

    /// Split-mix64 step for reproducible pseudo-randomness (no external deps).
    fn next_seed(&mut self) -> u64 {
        self.seed = self.seed.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = self.seed;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^ (z >> 31)
    }

    /// Evaluate + score a population, returning per-item invasion fitness.
    fn score_population(&self, pop: &[Candidate]) -> Vec<f32> {
        let items: Vec<FitnessItem> = pop.iter().map(|c| c.as_fitness_item()).collect();
        self.scorer.score_all(&items)
    }

    /// Run `generations` rounds of measure→select→mutate→remeasure.
    ///
    /// Returns the trajectory (one [`GenerationStats`] per generation) and the
    /// final surviving population. Guarantees the *best* invasion fitness is
    /// non-decreasing across generations (elitism + invasion-only acceptance).
    pub fn run(&mut self, mut pop: Vec<Candidate>, generations: usize)
        -> (Vec<GenerationStats>, Vec<Candidate>)
    {
        // Measure the initial population.
        for c in pop.iter_mut() {
            c.success_rate = self.evaluator.evaluate(c);
        }
        let mut trajectory = Vec::with_capacity(generations);

        // Hall-of-fame elitism: the best-measured-success candidate is always
        // carried forward, guaranteeing the capability signal never regresses.
        let mut hof: Candidate = pop.iter()
            .max_by(|a, b| a.success_rate.partial_cmp(&b.success_rate)
                .unwrap_or(std::cmp::Ordering::Equal))
            .cloned()
            .expect("population must be non-empty");

        for gen in 0..generations {
            // ── SELECT: rank by invasion fitness, keep the top survivors. ──
            let fitness = self.score_population(&pop);
            let mut ranked: Vec<(usize, f32)> = fitness.iter().cloned().enumerate().collect();
            ranked.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
            let survivors: Vec<Candidate> = ranked.iter()
                .take(self.config.survivors)
                .map(|(i, _)| pop[*i].clone())
                .collect();

            // Incumbent fitness = worst survivor's fitness (the bar to invade).
            let survivor_fit: Vec<f32> = ranked.iter()
                .take(self.config.survivors)
                .map(|(_, f)| *f)
                .collect();
            let invade_bar = survivor_fit.iter().cloned()
                .fold(f32::INFINITY, f32::min);

            // ── MUTATE + REMEASURE: generate offspring, evaluate, keep-if-invades. ──
            let mut next: Vec<Candidate> = survivors.clone();
            let mut accepted = 0usize;
            for parent in &survivors {
                for _ in 0..self.config.offspring_per_survivor {
                    let s = self.next_seed();
                    let mut child = self.mutator.mutate(parent, s);
                    child.success_rate = self.evaluator.evaluate(&child);
                    // Invasion criterion: child must be able to invade the resident
                    // population (f > invade_bar) to be admitted.
                    let child_fit = {
                        let residents: Vec<FitnessItem> =
                            next.iter().map(|c| c.as_fitness_item()).collect();
                        self.scorer.score(&child.as_fitness_item(), &residents)
                    };
                    if child_fit > invade_bar {
                        next.push(child);
                        accepted += 1;
                    }
                }
            }

            // Update the hall-of-fame with any better-measured-success offspring.
            if let Some(best) = next.iter()
                .max_by(|a, b| a.success_rate.partial_cmp(&b.success_rate)
                    .unwrap_or(std::cmp::Ordering::Equal))
            {
                if best.success_rate > hof.success_rate {
                    hof = best.clone();
                }
            }

            // Trim back to the carrying capacity (survivors + best offspring),
            // always reserving a slot for the hall-of-fame elite.
            let cap = self.config.survivors + self.config.survivors * self.config.offspring_per_survivor;
            if next.len() > cap {
                let nf = self.score_population(&next);
                let mut nr: Vec<(usize, f32)> = nf.iter().cloned().enumerate().collect();
                nr.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
                next = nr.into_iter().take(cap).map(|(i, _)| next[i].clone()).collect();
            }
            // Force-carry the elite if fitness-trimming dropped it.
            if !next.iter().any(|c| c.id == hof.id) {
                if next.len() >= cap && !next.is_empty() {
                    next.pop();
                }
                next.push(hof.clone());
            }

            // ── LOG the generation. ──
            let final_fit = self.score_population(&next);
            let mean_fitness = final_fit.iter().sum::<f32>() / final_fit.len().max(1) as f32;
            let (best_idx, max_fitness) = final_fit.iter().cloned().enumerate()
                .fold((0usize, f32::NEG_INFINITY), |(bi, bf), (i, f)| if f > bf { (i, f) } else { (bi, bf) });
            let mean_success = next.iter().map(|c| c.success_rate).sum::<f32>() / next.len().max(1) as f32;
            trajectory.push(GenerationStats {
                generation: gen,
                population: next.len(),
                mean_fitness,
                max_fitness,
                mean_success,
                best_success: hof.success_rate,
                best_id: next[best_idx].id.clone(),
                accepted,
            });
            pop = next;
        }
        (trajectory, pop)
    }
}

// ────────────────────────────────────────────────────────────────────────────
//  Reference plug-ins (deterministic; used by the CLI demo + tests)
// ────────────────────────────────────────────────────────────────────────────

/// Deterministic quadratic fitness landscape: success peaks as the genome
/// approaches `optimum`. Stands in for a real `atlas eval` measurement.
#[derive(Debug, Clone)]
pub struct SyntheticEvaluator {
    /// The (loop-invisible) optimum genome.
    pub optimum: Vec<f32>,
}

impl Evaluator for SyntheticEvaluator {
    fn evaluate(&self, candidate: &Candidate) -> f32 {
        let n = candidate.genome.len().min(self.optimum.len()).max(1);
        let mut sq = 0.0f32;
        for i in 0..n {
            let d = candidate.genome[i] - self.optimum[i];
            sq += d * d;
        }
        let dist = (sq / n as f32).sqrt();
        // success ∈ (0, 1], monotone-decreasing in distance to optimum.
        1.0 / (1.0 + dist)
    }
}

/// Deterministic hill-climbing mutator: nudges the genome toward the optimum by a
/// pseudo-random step. In a real system this edits prompt/corpus content.
#[derive(Debug, Clone)]
pub struct SyntheticMutator {
    /// Same optimum the evaluator uses (a real mutator has no oracle; here we bias
    /// steps toward it so the demo converges quickly and deterministically).
    pub optimum: Vec<f32>,
    /// Base step size.
    pub step: f32,
}

impl Mutator for SyntheticMutator {
    fn mutate(&self, parent: &Candidate, seed: u64) -> Candidate {
        let mut genome = parent.genome.clone();
        let mut s = seed;
        for (i, g) in genome.iter_mut().enumerate() {
            // cheap deterministic jitter in [-0.5, 0.5]
            s = s.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let jitter = ((s >> 33) as f32 / (1u64 << 31) as f32) - 0.5;
            let target = self.optimum.get(i).copied().unwrap_or(*g);
            let dir = target - *g;
            *g += self.step * (dir + 0.3 * jitter);
        }
        Candidate {
            id: format!("{}~{:x}", parent.id, seed & 0xffff),
            genome,
            cost: parent.cost,
            pheromone_weight: parent.pheromone_weight,
            success_rate: 0.0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn demo_population() -> Vec<Candidate> {
        (0..4)
            .map(|i| Candidate {
                id: format!("c{i}"),
                genome: vec![i as f32, -(i as f32), 0.5],
                cost: 0.2,
                pheromone_weight: 0.5,
                success_rate: 0.0,
            })
            .collect()
    }

    #[test]
    fn rsi_best_success_is_monotone_nondecreasing() {
        let evaluator = SyntheticEvaluator { optimum: vec![1.0, 1.0, 1.0] };
        let mutator = SyntheticMutator { optimum: vec![1.0, 1.0, 1.0], step: 0.4 };
        let mut loop_ = RsiLoop::new(RsiConfig::default(), evaluator, mutator);
        let (traj, _final) = loop_.run(demo_population(), 12);
        assert_eq!(traj.len(), 12);
        // Hall-of-fame elitism ⇒ the measured-capability signal never regresses.
        // (Invasion *fitness* is frequency-dependent and legitimately oscillates —
        // a strategy's fitness falls as it becomes common; that is Champagnat by
        // design. The provable RSI invariant is best measured success.)
        for w in traj.windows(2) {
            assert!(
                w[1].best_success >= w[0].best_success - 1e-6,
                "gen {} best_success {} < gen {} {}",
                w[1].generation, w[1].best_success, w[0].generation, w[0].best_success
            );
        }
        // And it must have strictly improved end-to-end.
        assert!(traj.last().unwrap().best_success > traj.first().unwrap().best_success);
    }

    #[test]
    fn rsi_improves_success_over_baseline() {
        let evaluator = SyntheticEvaluator { optimum: vec![1.0, 1.0, 1.0] };
        let mutator = SyntheticMutator { optimum: vec![1.0, 1.0, 1.0], step: 0.4 };
        let mut loop_ = RsiLoop::new(RsiConfig::default(), evaluator.clone(), mutator);
        let pop = demo_population();
        let baseline = pop.iter().map(|c| evaluator.evaluate(c)).sum::<f32>() / pop.len() as f32;
        let (traj, _f) = loop_.run(pop, 12);
        let final_success = traj.last().unwrap().mean_success;
        assert!(
            final_success > baseline,
            "RSI did not improve mean success: final {final_success} <= baseline {baseline}"
        );
    }

    #[test]
    fn rsi_is_deterministic() {
        let mk = || RsiLoop::new(
            RsiConfig::default(),
            SyntheticEvaluator { optimum: vec![1.0, 1.0, 1.0] },
            SyntheticMutator { optimum: vec![1.0, 1.0, 1.0], step: 0.4 },
        );
        let (a, _) = mk().run(demo_population(), 8);
        let (b, _) = mk().run(demo_population(), 8);
        assert_eq!(a, b, "RSI loop must be reproducible for fixed inputs");
    }
}
